name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  owesome_validator: ^0.0.5
  firebase_auth: ^4.15.2
  shared_preferences: ^2.2.2
  razorpay_flutter: ^1.2.3
  material: ^1.0.0+2
  flutter_typeahead: ^5.0.0
  flutter_native_splash: ^2.3.6
  _flutterfire_internals: ^1.3.16
  cloud_firestore: ^4.13.5
  firebase_rules_convert: ^0.1.2
  cloud_firestore_web: ^3.8.7
  firebase_auth_web: ^5.8.11
  firebase_core: ^2.24.2
  firebase_core_web: ^2.10.0
  firebase_database: ^10.3.8
  material_color_utilities: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/image-1.png
    - assets/page-1/images/image-6.png
    - assets/page-1/images/image-6-9Wh.png
    - assets/page-1/images/image-6-EJm.png
    - assets/page-1/images/angle-left.png
    - assets/page-1/images/image-6-xjb.png
    - assets/page-1/images/eye-off.png
    - assets/page-1/images/top-status-bar.png
    - assets/page-1/images/top-status-bar-8Wu.png
    - assets/page-1/images/map.png
    - assets/page-1/images/eye-off-CbT.png
    - assets/page-1/images/eye-off-Ca5.png
    - assets/page-1/images/auto-group-pbzb.png
    - assets/page-1/images/angle-left-EU1.png
    - assets/page-1/images/angle-left-8JV.png
    - assets/page-1/images/top-status-bar-vJD.png
    - assets/page-1/images/angle-left-5mK.png
    - assets/page-1/images/up-arrow.png
    - assets/page-1/images/top-status-bar-JrD.png
    - assets/page-1/images/top-status-bar-3Ms.png
    - assets/page-1/images/up-arrow-Gvm.png
    - assets/page-1/images/top-status-bar-E9P.png
    - assets/page-1/images/auto-group-wijd.png
    - assets/page-1/images/top-status-bar-a5P.png
    - assets/page-1/images/angle-left-uo7.png
    - assets/page-1/images/eye-off-E6d.png
    - assets/page-1/images/up-arrow-7db.png
    - assets/page-1/images/eye-off-VUD.png
    - assets/page-1/images/map-p2d.png
    - assets/page-1/images/eye-off-kPj.png
    - assets/page-1/images/angle-left-3wf.png
    - assets/page-1/images/up-arrow-yqj.png
    - assets/page-1/images/up-arrow-CPb.png
    - assets/page-1/images/eye-off-ycu.png
    - assets/page-1/images/eye-off-fe9.png
    - assets/page-1/images/eye-off-nXb.png
    - assets/page-1/images/angle-left-YU9.png
    - assets/page-1/images/top-status-bar-tEu.png
    - assets/page-1/images/angle-left-uZK.png
    - assets/page-1/images/eye-off-k89.png
    - assets/page-1/images/eye-off-3Hs.png
    - assets/page-1/images/eye-off-QfT.png
    - assets/page-1/images/eye-off-AWM.png
    - assets/page-1/images/down-arrow.png
    - assets/page-1/images/ridewave-high-resolution-logo-black-transparent.png
    - assets/page-1/images/ridewave-high-resolution-logo-white-transparent (1).png

flutter_native_splash:
  color: "#4CAF50"  # Your green color
  fill: true
  android: true
  ios: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
