import 'package:flutter/material.dart';
import 'package:myapp/util/database.dart';
import 'package:myapp/page-1/home.dart';

const kPrimaryColor = Color(0xff008955);

class AddRide extends StatefulWidget {
  const AddRide({Key? key}) : super(key: key);

  @override
  _AddRideState createState() => _AddRideState();
}

class _AddRideState extends State<AddRide> {
  String selectedGender = 'None';
  String selectedTime = '10:00 AM';
  TextEditingController startLocationController = TextEditingController();
  TextEditingController endLocationController = TextEditingController();
  TextEditingController priceController = TextEditingController();

  @override
  void dispose() {
    startLocationController.dispose();
    endLocationController.dispose();
    priceController.dispose();
    super.dispose();
  }

  List<String> locations = [
    'IBA MAIN CAMPUS',
    'IBA CITY CAMPUS',
    '2 TALWAR',
    '3 TALWAR',
    '4K CHOWRANGI',
    '70 CLIFTON',
    'ABB TAKK TV HEAD OFFICE',
    'ABDULLAH HAROON ROAD',
    'ABID TOWN',
    'ABU HASSAN ASPHANI ROAD',
    'ADAMJEE NAGAR',
    'AF GARDEN',
    'AGHA KHAN HOSPITAL',
    'AHSAN ABAD',
    'AI GARH SOCIETY SCHEEM 33',
    'AL AZHAR GARDEN',
    'AL HAMRA SOCIETY',
    'AL HILAL SOCIETY',
    'AL MANZAR TOWER',
    'AL NOOR SOCIETY',
    'AL NOOR TERMINAL',
    'AL RAHIM OIL TERMINAL',
    'ALAMGIR ROAD',
    'ALAMGIR SOCIETY',
    'ALI GARH SOCIETY',
    'ALI HIGHTS COMPLEX',
    'ALLAH WALA TOWN',
    'AMROHA SOCIETY',
    'ANCHOLI',
    'ANDA MORE',
    'ARC TOWER',
    'ARMY HOUSING COLONY',
    'ARMY OFFICER HOUSING SCHEME',
    'ART COUNCIL',
    'ASKARI 1',
    'ASKARI 2',
    'ASKARI 3',
    'ASKARI 4',
    'ASKARI 5',
    'AZEEM PURA',
    'AZIZABAD',
    'BAHADURABAD',
    'BAHRIA AUDITORIUM',
    'BAHRIA COLLEGE',
    'BAHRIA COMPLEX',
    'BAHRIA TOWN PRECINCT 1',
    'BAHRIA TOWN PRECINCT 2',
    'BAHRIA TOWN PRECINCT 3',
    'BAHRIA TOWN PRECINCT 4',
    'BAHRIA TOWN PRECINCT 5',
    'BAHRIA TOWN PRECINCT 6',
    'BAHRIA TOWN PRECINCT 7',
    'BAHRIA TOWN PRECINCT 8',
    'BAHRIA TOWN PRECINCT 9',
    'BAHRIA TOWN PRECINCT 10',
    'BAHRIA TOWN PRECINCT 11',
    'BAHRIA TOWN PRECINCT 12',
    'BAHRIA TOWN PRECINCT 13',
    'BAHRIA TOWN PRECINCT 14',
    'BAHRIA TOWN PRECINCT 15',
    'BAHRIA TOWN PRECINCT 16',
    'BAHRIA TOWN PRECINCT 17',
    'BAHRIA TOWN PRECINCT 18',
    'BAHRIA TOWN PRECINCT 19',
    'BAHRIA TOWN PRECINCT 20',
    'BAHRIA TOWN PRECINCT 21',
    'BAHRIA TOWN PRECINCT 22',
    'BAHRIA TOWN PRECINCT 23',
    'BAHRIA TOWN PRECINCT 24',
    'BAHRIA TOWN PRECINCT 25',
    'BAHRIA TOWN PRECINCT 26',
    'BAHRIA TOWN PRECINCT 27',
    'BAHRIA TOWN PRECINCT 28',
    'BAHRIA TOWN PRECINCT 29',
    'BAHRIA TOWN PRECINCT 30',
    'BAHRIA UNIVERSITY STADIUM ROAD',
    'BANGLORE TOWN',
    'BARA BOARD',
    'BATHISLAND',
    'BEACH LUXURY',
    'BEACON HOUSE SCHOOL JUBILEE CAMPUS NASRA SCHOOL',
    'BHITTAI COLONY',
    'BILAWAL HOUSE',
    'BMCHS BLOCK 3',
    'BMCHS BLOCK 7',
    'BMCHS BLOCK 8',
    'BOATBASIN',
    'BROOKS PHARMA PVT LTD ARTISTIC GARMENTS INDUSTRIES',
    'BUFFER ZONE 15 A1',
    'BUFFER ZONE 15 A2',
    'BUFFER ZONE 15 A3',
    'BUFFER ZONE 15 A4',
    'BUFFER ZONE 15 A5',
    'BUFFER ZONE 15 B',
    'BURNS ROAD',
    'BYJCHS BLOCK 3',
    'BYJCHS BLOCK 7',
    'BYJCHS BLOCK 8',
    'CAA COLONY',
    'CANTT BAZAR',
    'CANTT KHI',
    'CBM UNIVERSITY INDUS HOSPITAL',
    'CENTER POINT',
    'CENTRAL HOUSING SOCIETY',
    'CHAMRA SHAN CHOWRANGI',
    'CHANDNI CHOWK',
    'CITIZEN FOUNDATION HEAD OFFICE',
    'CIVIL HOSPITAL KHI',
    'CIVIL LINES',
    'CLIFTON BLOCK 1',
    'CLIFTON BLOCK 2',
    'CLIFTON BLOCK 3',
    'CLIFTON BLOCK 4',
    'CLIFTON BLOCK 5',
    'CLIFTON BLOCK 6',
    'CLIFTON BLOCK 7',
    'CLIFTON BLOCK 8',
    'CLIFTON BLOCK 9',
    'CM HOUSE',
    'CMH HOSPITAL',
    'COMMANDER HEIGHTS',
    'COUNTRY CLUB',
    'CP BERAR 3',
    'CP BERAR 7',
    'CP BERAR 8',
    'CUSTOM CHS',
    'DAR UL AMAN SOCIETY',
    'DAR UL SALAM',
    'DARUL ALOOM',
    'DASTAGIR',
    'DAWOOD POTA ROAD',
    'DAWOOD SOCIETY',
    'DEFENCE GARDEN',
    'DEFENCE VIEW KHI PHASE 1',
    'DEFENCE VIEW KHI PHASE 2',
    'DEFENCE VIEW KHI PHASE 3',
    'DEHLI COLONY',
    'DHA KHI PHASE 1',
    'DHA KHI PHASE 2',
    'DHA KHI PHASE 2 EXTENTION',
    'DHA KHI PHASE 4',
    'DHA KHI PHASE 5',
    'DHA KHI PHASE 5 EXTENTION',
    'DHA KHI PHASE 5 KHY SHAMSHEER',
    'DHA KHI PHASE 5 KHY TANZEEM',
    'DHA KHI PHASE 5C STREET',
    'DHA KHI PHASE 5D STREET',
    'DHA KHI PHASE 5E STREET',
    'DHA KHI PHASE 6',
    'DHA KHI PHASE 7',
    'DHA KHI PHASE 7 EXTENTION',
    'DHA KHI PHASE 8',
    'DHORAJEE',
    'DIAMOND CITY',
    'DJ SCIENCE COLLEGE',
    'DMCHS BLOCK 3',
    'DMCHS BLOCK 7',
    'DMCHS BLOCK 8',
    'DO MINUTE CHOWRANGI',
    'DOCHS',
    'DOHS',
    'DOW UNIVERSITY HOSPITAL OJHA CAMPUS',
    'DR ZIAUDDIN AHMED ROAD',
    'DRIGH ROAD',
    'ELECTION COMMISSION OFFICE',
    'EMBASSY INN',
    'ENGLISH BISCUIT EBM',
    'FALAKNAZ PLAZA',
    'FALCON COMPLEX MALIR CANTT',
    'FALCON HOUSING SOCIETY',
    'FARHAN SOCIETY',
    'FATIMIYAH COLLEGE',
    'FATIMIYAH HOSPITAL',
    'FB AREA BLOCK NO 1',
    'FB AREA BLOCK NO 2',
    'FB AREA BLOCK NO 3',
    'FB AREA BLOCK NO 4',
    'FB AREA BLOCK NO 5',
    'FB AREA BLOCK NO 6',
    'FB AREA BLOCK NO 7',
    'FB AREA BLOCK NO 8',
    'FB AREA BLOCK NO 9',
    'FB AREA BLOCK NO 10',
    'FB AREA BLOCK NO 11',
    'FB AREA BLOCK NO 12',
    'FB AREA BLOCK NO 13',
    'FB AREA BLOCK NO 14',
    'FB AREA BLOCK NO 15',
    'FB AREA BLOCK NO 16',
    'FB AREA BLOCK NO 17',
    'FB AREA BLOCK NO 18',
    'FB AREA BLOCK NO 19',
    'FB AREA BLOCK NO 20',
    'FB AREA BLOCK NO 21',
    'FB AREA BLOCK NO 22',
    'FC AREA',
    'FERRER TOWN',
    'FIRDOUS COLONY',
    'FLORIDA HOMES',
    'GABOL TOWN',
    'GALAXY APPARTMENT',
    'GARDEN EAST',
    'GARDEN JAMAT KHANA',
    'GARDEN WEST',
    'GAWALIR SOCIETY',
    'GETZ PHARMA PVT LTD',
    'GHAFOORIA RESIDENCY',
    'GODAM BROOKS CHOWRANGI',
    'GODHRA',
    'GOHAR RESIDENCIA & SHOPPING CENTRE',
    'GOVERNER HOUSE',
    'GREEN TOWN',
    'GUL PLAZA SHOPPING MALL',
    'GULBAHAR',
    'GULBERG',
    'GULISTAN E JOHAR 8A',
    'GULISTAN E JOHAR 9A',
    'GULISTAN E JOHAR 16A',
    'GULISTAN E JOHAR 17',
    'GULISTAN E JOHAR 18',
    'GULISTAN E JOHAR 19',
    'GULISTAN E JOHAR 20',
    'GULISTAN E JOHAR 8',
    'GULISTAN SOCIETY',
    'GULISTANE JOHAR 1',
    'GULISTANE JOHAR 2',
    'GULISTANE JOHAR 3',
    'GULISTANE JOHAR 4',
    'GULISTANE JOHAR 5',
    'GULISTANE JOHAR 6',
    'GULISTANE JOHAR 7',
    'GULISTANE JOHAR 9',
    'GULISTANE JOHAR 10',
    'GULISTANE JOHAR 11',
    'GULISTANE JOHAR 12',
    'GULISTANE JOHAR 13',
    'GULISTANE JOHAR 14',
    'GULISTANE JOHAR 15',
    'GULISTANE JOHAR 16',
    'GULSHAN BLOCK 14',
    'GULSHAN E ERUM',
    'GULSHAN E GHAZIAN',
    'GULSHAN E JAMAL',
    'GULSHAN E MAYMAR',
    'GULSHAN E ROMI',
    'GULSHAN E UMAIR',
    'GULSHAN E USMAN',
    'GULSHAN IQBAL BLOCK NO 1',
    'GULSHAN IQBAL BLOCK NO 2',
    'GULSHAN IQBAL BLOCK NO 3',
    'GULSHAN IQBAL BLOCK NO 4',
    'GULSHAN IQBAL BLOCK NO 4A',
    'GULSHAN IQBAL BLOCK NO 5',
    'GULSHAN IQBAL BLOCK NO 6',
    'GULSHAN IQBAL BLOCK NO 7',
    'GULSHAN IQBAL BLOCK NO 8',
    'GULSHAN IQBAL BLOCK NO 9',
    'GULSHAN IQBAL BLOCK NO 10',
    'GULSHAN IQBAL BLOCK NO 10A',
    'GULSHAN IQBAL BLOCK NO 11',
    'GULSHAN IQBAL BLOCK NO 12',
    'GULSHAN IQBAL BLOCK NO 13',
    'GULSHAN IQBAL BLOCK NO 13A',
    'GULSHAN IQBAL BLOCK NO 13B',
    'GULSHAN IQBAL BLOCK NO 13C',
    'GULSHAN IQBAL BLOCK NO 13D1',
    'GULSHAN IQBAL BLOCK NO 13D2',
    'GULSHAN IQBAL BLOCK NO 13D3',
    'GULSHAN IQBAL BLOCK NO 13E',
    'GULSHAN IQBAL BLOCK NO 13G',
    'GULSHAN IQBAL BLOCK NO 15',
    'GULSHAN IQBAL BLOCK NO 16',
    'GULSHAN IQBAL BLOCK NO 17',
    'GULSHAN IQBAL BLOCK NO 18',
    'GULSHAN IQBAL BLOCK NO 19',
    'GULSHAN IQBAL BLOCK NO 20',
    'GURU MANDIR',
    'HABIB CHOWRANGI',
    'HADIYAABAD',
    'HALARI MEMON SOCIETY',
    'HAMITCHEIKH PHOTOEYE COTTON SOCIETY',
    'HAROON BUNGALOW PHASE 1',
    'HAROON BUNGALOW PHASE 2',
    'HAVEN CITY',
    'HIGH COURT',
    'HOCKEY STADIUM',
    'HOLY FAMILY',
    'HOTEL GALAXY',
    'HOTEL MEHRAN',
    'HUSSAINABAD',
    'HUSSAINI SOCIETY BLOCK 3',
    'HUSSAINI SOCIETY BLOCK 7',
    'HUSSAINI SOCIETY BLOCK 8',
    'HYDERABAD COLONY',
    'ICI PAKISTAN',
    'IGLOO ICE CREAMORIENT ENERGY SYSTEM PVT LTD',
    'II CHUNDRIGARH ROAD',
    'IMTIAZ STORE QAYYUMABAD',
    'INARA GARDEN',
    'IQRA UNIVERSITY DEFENCE VIEW',
    'JAMA CLOTH MARKET',
    'JAMAT KHANA',
    'JAMSHED ROAD',
    'JAMSHED TOWN',
    'JAWENI HIGHTS',
    'JCHS',
    'JINNAH COURT',
    'JINNAH MEDICAL DENTAL COLLEGE',
    'JOHAR COMPLEX',
    'JUBILEE CLOTH MARKET',
    'KAECHS BLOCK 1',
    'KAECHS BLOCK 2',
    'KAECHS BLOCK 3',
    'KAECHS BLOCK 4',
    'KAECHS BLOCK 5',
    'KAECHS BLOCK 6',
    'KAECHS BLOCK 7',
    'KAECHS BLOCK 8',
    'KAGHAN SOCIETY KOKEN SOCIETY',
    'KANEEZ FATIMA',
    'KARACHI BAR SOCIETY',
    'KARACHI BOAT CLUB',
    'KARACHI GYM KHANA',
    'KARACHI UNI SOCIETY',
    'KARACHI UNIVERSITY',
    'KARACHI UNIVERSITY BOYS HOSTEL',
    'KARACHI UNIVERSITY CHINA HOSTEL',
    'KARACHI UNIVERSITY GIRLS HOSTEL',
    'KARACHI UNIVERSITY IBA',
    'KARACHI ZOO',
    'KAREEMABAD',
    'KARSAAZ',
    'KASHMIR ROAD',
    'KAZIMABAD',
    'KCHS',
    'KDA EXT',
    'KDA FLAT',
    'KDA OFFICER SOCIETY BLOCK NO A',
    'KDA OFFICER SOCIETY BLOCK NO B',
    'KDA SCHEME 1',
    'KDA SOCIETY KORANGI',
    'KHADDA MARKET DHA PHASE 5',
    'KHARA DAR',
    'KHATIWAR SOCIETY',
    'KHATRI SOCITEY',
    'KHAYABAN E SHAREEF',
    'KIDNEY CENTRE',
    'KIRAN HOSPITAL',
    'KMC WORK SHOP',
    'KMCHS BLOCK 3',
    'KMCHS BLOCK 7',
    'KMCHS BLOCK 8',
    'KOKAN GROUND',
    'KOKAN SOCIETY',
    'KORANGI 1',
    'KORANGI 2',
    'KORANGI 3',
    'KORANGI 4',
    'KORANGI 5',
    'KORANGI 6',
    'KORANGI CREEK HOSPITAL',
    'KORANGI CROSSING',
    'KPT SCHOOL',
    'LAKSON SQUARE 1',
    'LAKSON SQUARE 2',
    'LAKSON SQUARE 3',
    'LAL QILA AWAMI MARKAZ',
    'LALA ZAR',
    'LALUKHET',
    'LANDHI 1',
    'LANDHI 2',
    'LANDHI 3',
    'LANDHI 4',
    'LANDHI 5',
    'LANDHI 6',
    'LAYWERS COLONY',
    'LE MENDOZA PHARMACEUTICALS PVT LTD',
    'LIAQUAT NATIONAL HOSPITAL',
    'LIAQUATABAD',
    'LIGHT HOUSE',
    'LUCKNOW SOCIETY',
    'LUCKY STAR',
    'MACHS',
    'MAI KULACHI ROAD',
    'MAKHDOOM BILAWAL SOCIETY',
    'MALIK SOCIETY',
    'MALIR CANTT PHASE 1',
    'MALIR CANTT PHASE 2',
    'MALL SQUARE',
    'MARTIN DOW LIMITED',
    'MASHRIQI SOCIETY',
    'MEDICARE HOSPITAL',
    'MEERUT COOPERATIVE SOCIETY',
    'MEETHA DAR',
    'MEMON COLONY',
    'MEMON HOSPITAL',
    'MERCHANT NAVY SOCIETY',
    'MODEL COLONY',
    'MOSAMIAT',
    'MT KHAN ROAD',
    'MUHAMMAD PUR SOCIETY',
    'MUSLIMABAD',
    'NAGAN CHOWRANGI',
    'NAHEED SUPER STORE BAHADURABAD',
    'NASEEM COOPERATIVE HOUSING SOCIETY',
    'NASEERABAD',
    'NATIONAL STADIUM',
    'NATIONAL STADIUM COLONY',
    'NATIVE JETTY BRIDGE',
    'NAVAL COLONY',
    'NAVAL HOUSING SCHEME',
    'NAVY HOUSING SCHEME',
    'NAYA NAZIMABAD',
    'NAZ PLAZA',
    'NAZIMABAD NO 1',
    'NAZIMABAD NO 2',
    'NAZIMABAD NO 3',
    'NAZIMABAD NO 4',
    'NAZIMABAD NO 5',
    'NED STAFF COLONY',
    'NED UNIVERSITY',
    'NEELAM COLONY',
    'NEW ANCHOLI HOUSING SOCIETY',
    'NEW KARACHI',
    'NEW KARACHI INDUSTERIAL AREA',
    'NEW KARACHI SECTOR 5D',
    'NEW KARACHI SECTOR 5E',
    'NEW KARACHI SECTOR 5F',
    'NEW KARACHI SECTOR 5G',
    'NEW KARACHI SECTOR 5I',
    'NEW KARACHI SECTOR 5J',
    'NEW KARACHI SECTOR 5L',
    'NEW KARACHI SECTOR 5M',
    'NEW KARACHI SECTOR 11E',
    'NEW KARACHI SECTOR 11I',
    'NEW KARACHI SECTOR 11L',
    'NEW RIZVIA SOCIETY',
    'NEW TOWN',
    'NHS PHASE 1',
    'NHS PHASE 2',
    'NHS PHASE 3',
    'NHS PHASE 4',
    'NICL BUILDING',
    'NISHTER ROAD',
    'NKCHS',
    'NORE 1',
    'NORTH KARACHI SECTOR 5 A1',
    'NORTH KARACHI SECTOR 5 A2',
    'NORTH KARACHI SECTOR 5 A3',
    'NORTH KARACHI SECTOR 5 A4',
    'NORTH KARACHI SECTOR 5 B1',
    'NORTH KARACHI SECTOR 5 B2',
    'NORTH KARACHI SECTOR 5 B3',
    'NORTH KARACHI SECTOR 5 B4',
    'NORTH KARACHI SECTOR 5 C1',
    'NORTH KARACHI SECTOR 5 C2',
    'NORTH KARACHI SECTOR 5 C3',
    'NORTH KARACHI SECTOR 5 C4',
    'NORTH KARACHI SECTOR 7A',
    'NORTH KARACHI SECTOR 7B',
    'NORTH KARACHI SECTOR 7C',
    'NORTH KARACHI SECTOR 7D',
    'NORTH KARACHI SECTOR 8',
    'NORTH KARACHI SECTOR 9',
    'NORTH KARACHI SECTOR 10',
    'NORTH KARACHI SECTOR 11A',
    'NORTH KARACHI SECTOR 11B',
    'NORTH KARACHI SECTOR 11C',
    'NORTH NAZIMABAD A',
    'NORTH NAZIMABAD B',
    'NORTH NAZIMABAD C',
    'NORTH NAZIMABAD D',
    'NORTH NAZIMABAD E',
    'NORTH NAZIMABAD F',
    'NORTH NAZIMABAD G',
    'NORTH NAZIMABAD H',
    'NORTH NAZIMABAD I',
    'NORTH NAZIMABAD J',
    'NORTH NAZIMABAD K',
    'NORTH NAZIMABAD L',
    'NORTH NAZIMABAD M',
    'NORTH NAZIMABAD N',
    'NORTH NAZIMABAD O',
    'NORTH NAZIMABAD P',
    'NORTH NAZIMABAD Q',
    'NORTH NAZIMABAD R',
    'NORTH NAZIMABAD S',
    'NORTH NAZIMABAD T',
    'NORTH NAZIMABAD W',
    'NORTH TOWN RESIDENCY',
    'NUMAISH',
    'NUST UNIVERSITY',
    'OCHS BLOCK 3',
    'OCHS BLOCK 7',
    'OCHS BLOCK 8',
    'OCS PAKISTAN MULTINET',
    'OLD CLIFTON',
    'OMI HOSPITAL',
    'PAF BASE FAISAL',
    'PAF FAISAL',
    'PAK COLONY',
    'PAKISTAN AUDIT CHS',
    'PAKISTAN CHOWK',
    'PAKISTAN STATE OIL TERMINAL A',
    'PAKOLA MASJID',
    'PAPOSH NAGAR',
    'PARKO KIMARI TERMINAL',
    'PASSPORT OFFICE',
    'PATEL PARA',
    'PCSIR 2',
    'PECHS BLOCK 2',
    'PECHS BLOCK 3',
    'PECHS BLOCK 6',
    'PEPSI COMPANY',
    'PHILI BHIT SOCITY',
    'PIA SOCIETY',
    'PIB COLONY',
    'PIDC',
    'PIDC COLONY',
    'PNS BASE MEHRAN',
    'PNS SHIFA PHASE NO 2 DHA KHI',
    'PNSC BUILDING',
    'PNT COLONY',
    'PNT SOCIETY KORANGI',
    'PORT GRAND',
    'PORT OIL TERMINAL',
    'PORT TRUCK STAND',
    'POWER HOUSE',
    'PREM VILLAS PHASE 1',
    'PREM VILLAS PHASE 2',
    'PRESS CLUB',
    'PRINCE ALI S KHAN APPARTMENT',
    'PROFELLOR GATE',
    'PSO HOUSE',
    'PTV SOCIETY',
    'PUNJAB COLONY',
    'PUNJABI SODIGHRAN',
    'QAYYUMABAD',
    'QTCHS',
    'QUETTA LANE',
    'QUETTA TOWN 1',
    'QUETTA TOWN 2',
    'RACE COURCE',
    'RAFA E AAM',
    'RAHEEM VIEW',
    'RAINBOW SOCIETY',
    'RAINBOW TOWER',
    'RANCHOR LINE',
    'REGAL CHOWK',
    'RIM JHIM TOWER',
    'RIZVIA SOCIETY',
    'ROTI CORPORATION',
    'SAADI TOWN',
    'SADDAR MOBILE MARKET',
    'SAFOORA',
    'SAIMA ARABIAN VILLAS',
    'SALEEM CENTER',
    'SALFIA SOCIETY',
    'SANOBAR COTTAGE',
    'SANOFI AVENTIS',
    'SARA TOWN',
    'SCHEME NO 35 NAWAZ SHAREEF SCHEME',
    'SCHEME NO 35 PIA SCHEME',
    'SEA VIEW APPARTMENTS',
    'SERENA VILLAG',
    'SHABBIRABAD BLOCK A',
    'SHABBIRABAD BLOCK B',
    'SHADMAN TOWN SECTOR 14A',
    'SHADMAN TOWN SECTOR 14B',
    'SHAH FAISAL COLONY NO 1',
    'SHAH FAISAL COLONY NO 2',
    'SHAH FAISAL COLONY NO 3',
    'SHAH FAISAL COLONY NO 4',
    'SHAH FAISAL COLONY NO 5',
    'SHAHDAB ARCADE',
    'SHAHEED E MILLAT ROAD',
    'SHAHEEN COMPLEX',
    'SHAMIR RESIDENCY',
    'SHAMSI HOUSING SOCIETY',
    'SHANZIL GOLF RESIDENCY',
    'SHARAFABAD',
    'SHAREEFABAD',
    'SHAZ BANGLOWS',
    'SHEEREN JINNAH POST OFFICE',
    'SHEIKH ZAYED',
    'SHELL HOUSE',
    'Shell Oil Terminal',
    'SHELL OIL TERMINAL A',
    'SIEMENS CHOWRANGI',
    'SINDH ASSEMBLY',
    'SINDH SECTRAITE SOCIETY',
    'SINGER CHOWRANGI INDUS CHOWRANGI',
    'SINGER COMPANY',
    'SMCHS BLOCK A',
    'SMCHS BLOCK B',
    'SOLDIER BAZAR',
    'SOMORRO SOCITY',
    'SONI RESORT',
    'SOORTY ENTERPRISES BIKIYA INDUTRIES',
    'SRE MAJEED DALMIYA ROAD',
    'STAFF COLONY',
    'STATE BANK SOCIETY',
    'STRANCHAN ROAD',
    'STUDIO 146 KARACHI COKE STUDIO',
    'SUPARCO HQ',
    'SUPARCO SOCIETY',
    'SUPER HIGHWAY',
    'SURJANI TOWN',
    'SURJANI TOWN SECTOR 1',
    'SURJANI TOWN SECTOR 4',
    'SURJANI TOWN SECTOR 5',
    'SYLVANA PAKISTAN MEHRAN SPICE & FOOD',
    'TABBA HEART CLINIC',
    'TABBA KIDNY CLINIC',
    'TARIQ BIN ZAYAD COLONY',
    'TARIQ ROAD',
    'TAUHEED COMMERCIAL',
    'TEACHERS SOCIETY 1',
    'TEACHERS SOCIETY 2',
    'Test Area',
    'TIPU SULTAN ROAD',
    'TIPU SULTAN SOCIETY',
    'TRADING SOCIETY',
    'TV ROUNDABOUT',
    'TV STATION PTV',
    'UNCLE SARYA',
    'UP MORE',
    'URDU BAZAR NAZIMABAD',
    'URDU BAZAR NEAR LIGHT HOUSE',
    'USMAN ABAD',
    'USMAN PUBLIC SCHOOL',
    'USMANIA COLONY',
    'VITA CHOWRANGI BILAL CHOWRANGI',
    'WEST WHARF',
    'WRITERS GUILD SOCIETY',
    'YASEENABAD',
    'YMC GROUND',
    'ZAIB UN NISA STREET',
    'ZAINAB PANJWANI HOSPITAL',
    'ZAMAN TOWN',
    'ZAMZAMA COMMERCIAL',
    'ZAMZAMA PARK',
    'ZEHRA NAGAR SOCIETY',
    'ZENAT ABAD',
    'ZIA UDDIN HOSPITAL CLIFTON',
    'ZIA UDDIN HOSPITAL NAZIMABAD'

    // ... other locations
  ];

  List<String> endLocations = [];
  String startLocation = '';
  String endLocation = '';

  Future<void> selectTime(BuildContext context) async {
    final TimeOfDay? pickedTime = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.now(),
    );
    if (pickedTime != null && pickedTime != TimeOfDay.now()) {
      setState(() {
        selectedTime = pickedTime.format(context);
      });
    }
  }

  void selectLocation(BuildContext context, {required bool isStartLocation}) {
    showModalBottomSheet(
      context: context,
      builder: (BuildContext bc) {
        List<String> locationOptions = isStartLocation
            ? locations
            : locations.where((loc) => loc != startLocation).toList();

        if (!isStartLocation &&
            startLocation != 'IBA MAIN CAMPUS' &&
            startLocation != 'IBA CITY CAMPUS') {
          locationOptions = ['IBA MAIN CAMPUS', 'IBA CITY CAMPUS'];
        }

        return SafeArea(
          child: SingleChildScrollView(
            child: Wrap(
              children: locationOptions
                  .map((location) => ListTile(
                        title: Text(location),
                        onTap: () {
                          setState(() {
                            if (isStartLocation) {
                              startLocation = location;
                            } else {
                              endLocation = location;
                            }
                          });
                          Navigator.pop(context);
                        },
                      ))
                  .toList(),
            ),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: kPrimaryColor,
        title: const Text('Add Ride'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            DropdownButtonFormField<String>(
              value: selectedGender != 'None' ? selectedGender : null,
              hint: const Text('Gender Preference'),
              items: ['None', 'Male', 'Female'].map((String value) {
                return DropdownMenuItem<String>(
                  value: value,
                  child: Text(value),
                );
              }).toList(),
              onChanged: (newValue) {
                setState(() {
                  selectedGender = newValue!;
                });
              },
            ),
            ListTile(
              title: const Text('Select Start Location'),
              subtitle: Text(
                  startLocation.isNotEmpty ? startLocation : 'Tap to select'),
              onTap: () => selectLocation(context, isStartLocation: true),
            ),
            ListTile(
              title: const Text('Select End Location'),
              subtitle:
                  Text(endLocation.isNotEmpty ? endLocation : 'Tap to select'),
              onTap: () => selectLocation(context, isStartLocation: false),
            ),
            ListTile(
              title: const Text('Select Time'),
              subtitle: Text(selectedTime),
              onTap: () {
                selectTime(context);
              },
            ),
            TextFormField(
              controller: priceController,
              keyboardType: TextInputType.number,
              decoration: const InputDecoration(
                labelText: 'Set Price For Each Rider',
                border: OutlineInputBorder(),
              ),
            ),
            ElevatedButton(
  style: ElevatedButton.styleFrom(
    primary: kPrimaryColor,
    onPrimary: Colors.white,
  ),
  onPressed: () async {
    // Perform validation checks here
    if (startLocation.isNotEmpty &&
        endLocation.isNotEmpty &&
        startLocation != endLocation &&
        priceController.text.isNotEmpty &&
        double.tryParse(priceController.text) != null) {
      // If all validations pass, continue with the Firestore upload
      try {
        // Call your Firestore data upload function here
        await addRideDetails(
          startLocation,
          endLocation,
          selectedTime,
          selectedGender,
          double.parse(priceController.text), // Include the price
        );
        // Navigate to home page after successful upload
        Navigator.pushAndRemoveUntil(
          context,
          MaterialPageRoute(
              builder: (context) => HomePage(
                  userdata: {})), // Replace with your actual HomePage if it requires arguments
          (Route<dynamic> route) => false,
        );
      } catch (e) {
        // Handle errors, perhaps show a snackbar with the error
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to add ride: $e')),
        );
      }
    } else {
      // Show appropriate error messages if validations fail
      String errorMessage = 'Please correct the errors:';
      if (startLocation.isEmpty || endLocation.isEmpty) {
        errorMessage += '\n- Select different start and end locations.';
      }
      if (priceController.text.isEmpty || double.tryParse(priceController.text) == null) {
        errorMessage += '\n- Enter a valid price.';
      }
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(errorMessage)),
      );
    }
  },
  child: const Text('Continue'),
),
          ],
        ),
      ),
    );
  }
}

void main() {
  runApp(const MaterialApp(home: AddRide()));
}
